project:
  title: "CEU - Junio 26"
  type: "website"
  output-dir: docs

format:
  revealjs:
    theme: default
    slide-number: true

execute:
  echo: false
  warning: false
  message: false

website: 
  favicon: "img/favicon.png"
